apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: 590184068137.dkr.ecr.ap-northeast-2.amazonaws.com/demo-frontend
  newName: 590184068137.dkr.ecr.ap-northeast-2.amazonaws.com/demo-frontend
  newTag: 2b3bb82b
resources:
- ../../base
patchesStrategicMerge:
- front-deployment-patch.yaml
- front-service-patch.yaml
